easy_admin:
    site_name: 'Beu-Beu Art Festival Amministrazione'
    formats:
        datetime: 'd M Y H:i'
    design:
        brand_color: '000'
    entities:
        # List the entity class name you want to manage
        Mostra:
            class: App\Entity\Exhibit
            label: 'Mostre'
            form:
                fields: ['title', {property: 'imageFile', type: 'vich_image'}, 'description', 'year']
            list:
                title: 'Lista Mostre'
                fields: ['title', {property: 'image', type: 'image', base_path: '/uploads/images/exhibit/'}, 'created']
        Performance:
            class: App\Entity\Performance
            label: 'Concerti e Performance'
            form:
                fields: ['title', {property: 'imageFile', type: 'vich_image'}, 'description', 'whendate']
            list:
                title: 'Lista Performance'
                fields: ['title', {property: 'image', type: 'image', base_path: '/uploads/images/performance/'}, 'created']
        Incontri:
            class: App\Entity\Meeting
            label: 'Incontri'
            form:
                fields: ['title', {property: 'imageFile', type: 'vich_image'}, 'description', 'whendate']
            list:
                title: 'Lista Incontri'
                fields: ['title', {property: 'image', type: 'image', base_path: '/uploads/images/meeting/'}, 'created']
