easy_admin:
    site_name: 'Beu-Beu Art Festival Amministrazione'
    formats:
        datetime: 'd M Y H:i'
    design:
        brand_color: '000'
        assets:
            js:
                - '/summernote/summernote.js'
                - '/summernote/lang/summernote-it-IT.js'
                - '/summernote/mySummernote.js'
            css:
                - '/summernote/summernote.css'
    entities:
        # List the entity class name you want to manage
        Carousel:
            class: App\Entity\Carousel
            label: 'Carousel'
            form:
                fields: [{property: 'imageFile', type: 'vich_image', label: 'Immagine'}]
            list:
                title: 'Lista Immagini Carousel'
                fields: [{property: 'image', type: 'image', base_path: 'uploads/images/carousel/', label: 'Immagine'}, {property: 'created', 'label': 'Creato il' }]

        Programma:
            disabled_actions: ['new']
            class: App\Entity\Program
            label: 'Programma'
            form:
                fields: 
                  - {property: 'content', label: 'Contenuto', css_class: 'summernote'}
            list:
                title: Programma
                fields: 
                  - {property: 'content', label: 'Contenuto', type: 'raw'}
                actions: ['edit', '-delete']

        Mostra:
            class: App\Entity\Exhibit
            label: 'Mostre'
            form:
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'imageFile', type: 'vich_image', label: 'Immagine'}
                    #TODO: Trovare il modo di modificare la classe della Textarea
                  - {property: 'description', label: 'Descrizione', css_class: 'summernote'}
                  - {property: 'year', label: 'Anno'}
                  - {property: 'gallery1File', type: 'vich_image', label: 'Immagine Galleria 1'}
                  - {property: 'gallery2File', type: 'vich_image', label: 'Immagine Galleria 2'}
                  - {property: 'gallery3File', type: 'vich_image', label: 'Immagine Galleria 3'}
            list:
                title: 'Lista Mostre'
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'image', type: 'image', base_path: 'uploads/images/exhibit/', label: 'Immagine'}
                  - {property: 'created', label: 'Creato il'}
        Performance:
            class: App\Entity\Performance
            label: 'Concerti e Performance'
            form:
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'imageFile', type: 'vich_image', label: 'Immagine'}
                  - {property: 'description', label: 'Descrizione'}
                  - {property: 'whendate', label: 'Data', type_options: {'widget': 'single_text', 'format': 'dd/MM/yyyy H:mm', 'attr': {'class': 'js-datepicker'}}}
                  - {property: 'gallery1File', type: 'vich_image', label: 'Immagine Galleria 1'}
                  - {property: 'gallery2File', type: 'vich_image', label: 'Immagine Galleria 2'}
                  - {property: 'gallery3File', type: 'vich_image', label: 'Immagine Galleria 3'}
            list:
                title: 'Lista Performance'
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'image', type: 'image', base_path: 'uploads/images/performance/', label: 'Immagine'}
                  - {property: 'created', label: 'Creato il'}
        Incontri:
            class: App\Entity\Meeting
            label: 'Incontri'
            form:
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'imageFile', type: 'vich_image', label: 'Immagine'}
                  - {property: 'description', label: 'Descrizione'}
                  - {property: 'whendate', label: 'Data', type_options: {'widget': 'single_text', 'format': 'dd/MM/yyyy H:mm', 'attr': {'class': 'js-datepicker'}}}
                  - {property: 'gallery1File', type: 'vich_image', label: 'Immagine Galleria 1'}
                  - {property: 'gallery2File', type: 'vich_image', label: 'Immagine Galleria 2'}
                  - {property: 'gallery3File', type: 'vich_image', label: 'Immagine Galleria 3'}
            list:
                title: 'Lista Incontri'
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'image', type: 'image', base_path: 'uploads/images/meeting/', label: 'Immagine'}
                  - {property: 'created', label: 'Creato il'}
        Workshop:
            class: App\Entity\Workshop
            label: 'Workshop'
            form:
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'imageFile', type: 'vich_image', label: 'Immagine'}
                  - {property: 'description', label: 'Descrizione'}
                  - {property: 'whendate', label: 'Data', type_options: {'widget': 'single_text', 'format': 'dd/MM/yyyy H:mm', 'attr': {'class': 'js-datepicker'}}}
                  - {property: 'gallery1File', type: 'vich_image', label: 'Immagine Galleria 1'}
                  - {property: 'gallery2File', type: 'vich_image', label: 'Immagine Galleria 2'}
                  - {property: 'gallery3File', type: 'vich_image', label: 'Immagine Galleria 3'}
            list:
                title: 'Lista Workshop'
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'image', type: 'image', base_path: 'uploads/images/workshop/', label: 'Immagine'}
                  - {property: 'created', label: 'Creato il'}
        Interventi:
            class: App\Entity\Street
            label: 'Interventi Urbani'
            form:
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'imageFile', type: 'vich_image', label: 'Immagine'}
                  - {property: 'description', label: 'Descrizione'}
                  - {property: 'whendate', label: 'Data', type_options: {'widget': 'single_text', 'format': 'dd/MM/yyyy H:mm', 'attr': {'class': 'js-datepicker'}}}
                  - {property: 'gallery1File', type: 'vich_image', label: 'Immagine Galleria 1'}
                  - {property: 'gallery2File', type: 'vich_image', label: 'Immagine Galleria 2'}
                  - {property: 'gallery3File', type: 'vich_image', label: 'Immagine Galleria 3'}
            list:
                title: 'Lista Interventi Urbani'
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'image', type: 'image', base_path: 'uploads/images/street/', label: 'Immagine'}
                  - {property: 'created', label: 'Creato il'}
        Eventi:
            class: App\Entity\Event
            label: 'Eventi Collaterali'
            form:
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'imageFile', type: 'vich_image', label: 'Immagine'}
                  - {property: 'description', label: 'Descrizione'}
                  - {property: 'whendate', label: 'Data', type_options: {'widget': 'single_text', 'format': 'dd/MM/yyyy H:mm', 'attr': {'class': 'js-datepicker'}}}
                  - {property: 'gallery1File', type: 'vich_image', label: 'Immagine Galleria 1'}
                  - {property: 'gallery2File', type: 'vich_image', label: 'Immagine Galleria 2'}
                  - {property: 'gallery3File', type: 'vich_image', label: 'Immagine Galleria 3'}
            list:
                title: 'Lista Eventi Collaterali'
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'image', type: 'image', base_path: 'uploads/images/event/', label: 'Immagine'}
                  - {property: 'created', label: 'Creato il'}

        Abbey:
            disabled_actions: ['new']
            class: App\Entity\Abbey
            label: 'Abbazia'
            form:
                fields: 
                  - {property: 'content', label: 'Contenuto', css_class: 'summernote'}
            list:
                title: Abbazia
                fields: 
                  - {property: 'content', label: 'Contenuto', type: 'raw'}
                actions: ['edit', '-delete']

        Press:
            disabled_actions: ['new']
            class: App\Entity\Press
            label: 'Press'
            form:
                fields: 
                  - {property: 'content', label: 'Contenuto', css_class: 'summernote'}
            list:
                title: Press
                fields: 
                  - {property: 'content', label: 'Contenuto', type: 'raw'}
                actions: ['edit', '-delete']

        Collaboration:
            disabled_actions: ['new']
            class: App\Entity\Collaboration
            label: 'Collaborazioni'
            form:
                fields: 
                  - {property: 'content', label: 'Contenuto', css_class: 'summernote'}
            list:
                title: Collaborazioni
                fields: 
                  - {property: 'content', label: 'Contenuto', type: 'raw'}
                actions: ['edit', '-delete']

        About:
            disabled_actions: ['new']
            class: App\Entity\About
            label: 'About'
            form:
                fields: 
                  - {property: 'content', label: 'Contenuto', css_class: 'summernote'}
            list:
                title: About
                fields: 
                  - {property: 'content', label: 'Contenuto', type: 'raw'}
                actions: ['edit', '-delete']
