easy_admin:
    site_name: 'Beu-Beu Art Festival Amministrazione'
    formats:
        datetime: 'd M Y H:i'
    design:
        brand_color: '000'
    entities:
        # List the entity class name you want to manage
        Carousel:
            class: App\Entity\Carousel
            label: 'Carousel'
            form:
                fields: [{property: 'imageFile', type: 'vich_image', label: 'Immagine'}]
            list:
                title: 'Lista Immagini Carousel'
                fields: [{property: 'image', type: 'image', base_path: '/uploads/images/carousel/', label: 'Immagine'}, {property: 'created', 'label': 'Creato il' }]

        Mostra:
            class: App\Entity\Exhibit
            label: 'Mostre'
            form:
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'imageFile', type: 'vich_image', label: 'Immagine'}
                  - {property: 'description', label: 'Descrizione'}
                  - {property: 'year', label: 'Anno'}
                  - {property: 'gallery1File', type: 'vich_image', label: 'Immagine Galleria 1'}
                  - {property: 'gallery2File', type: 'vich_image', label: 'Immagine Galleria 2'}
                  - {property: 'gallery3File', type: 'vich_image', label: 'Immagine Galleria 3'}
            list:
                title: 'Lista Mostre'
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'image', type: 'image', base_path: '/uploads/images/exhibit/', label: 'Immagine'}
                  - {property: 'created', label: 'Creato il'}
        Performance:
            class: App\Entity\Performance
            label: 'Concerti e Performance'
            form:
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'imageFile', type: 'vich_image', label: 'Immagine'}
                  - {property: 'description', label: 'Descrizione'}
                  - {property: 'whendate', label: 'Data', type_options: {'widget': 'single_text', 'format': 'dd/MM/yyyy H:mm', 'attr': {'class': 'js-datepicker'}}}
                  - {property: 'gallery1File', type: 'vich_image', label: 'Immagine Galleria 1'}
                  - {property: 'gallery2File', type: 'vich_image', label: 'Immagine Galleria 2'}
                  - {property: 'gallery3File', type: 'vich_image', label: 'Immagine Galleria 3'}
            list:
                title: 'Lista Performance'
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'image', type: 'image', base_path: '/uploads/images/performance/', label: 'Immagine'}
                  - {property: 'created', label: 'Creato il'}
        Incontri:
            class: App\Entity\Meeting
            label: 'Incontri'
            form:
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'imageFile', type: 'vich_image', label: 'Immagine'}
                  - {property: 'description', label: 'Descrizione'}
                  - {property: 'whendate', label: 'Data', type_options: {'widget': 'single_text', 'format': 'dd/MM/yyyy H:mm', 'attr': {'class': 'js-datepicker'}}}
                  - {property: 'gallery1File', type: 'vich_image', label: 'Immagine Galleria 1'}
                  - {property: 'gallery2File', type: 'vich_image', label: 'Immagine Galleria 2'}
                  - {property: 'gallery3File', type: 'vich_image', label: 'Immagine Galleria 3'}
            list:
                title: 'Lista Incontri'
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'image', type: 'image', base_path: '/uploads/images/meeting/', label: 'Immagine'}
                  - {property: 'created', label: 'Creato il'}
        Workshop:
            class: App\Entity\Workshop
            label: 'Workshop'
            form:
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'imageFile', type: 'vich_image', label: 'Immagine'}
                  - {property: 'description', label: 'Descrizione'}
                  - {property: 'whendate', label: 'Data', type_options: {'widget': 'single_text', 'format': 'dd/MM/yyyy H:mm', 'attr': {'class': 'js-datepicker'}}}
            list:
                title: 'Lista Workshop'
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'image', type: 'image', base_path: '/uploads/images/workshop/', label: 'Immagine'}
                  - {property: 'created', label: 'Creato il'}
        Interventi:
            class: App\Entity\Street
            label: 'Interventi Urbani'
            form:
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'imageFile', type: 'vich_image', label: 'Immagine'}
                  - {property: 'description', label: 'Descrizione'}
                  - {property: 'whendate', label: 'Data', type_options: {'widget': 'single_text', 'format': 'dd/MM/yyyy H:mm', 'attr': {'class': 'js-datepicker'}}}
            list:
                title: 'Lista Interventi Urbani'
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'image', type: 'image', base_path: '/uploads/images/street/', label: 'Immagine'}
                  - {property: 'created', label: 'Creato il'}
        Eventi:
            class: App\Entity\Event
            label: 'Eventi Collaterali'
            form:
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'imageFile', type: 'vich_image', label: 'Immagine'}
                  - {property: 'description', label: 'Descrizione'}
                  - {property: 'whendate', label: 'Data', type_options: {'widget': 'single_text', 'format': 'dd/MM/yyyy H:mm', 'attr': {'class': 'js-datepicker'}}}
            list:
                title: 'Lista Eventi Collaterali'
                fields: 
                  - {property: 'title', label: 'Titolo'}
                  - {property: 'image', type: 'image', base_path: '/uploads/images/event/', label: 'Immagine'}
                  - {property: 'created', label: 'Creato il'}
