vich_uploader:
    db_driver: orm

    mappings:
        exhibit_images:
            uri_prefix: /uploads/images/exhibit
            upload_destination: '%kernel.project_dir%/public/uploads/images/exhibit'
