vich_uploader:
    db_driver: orm

    mappings:
        exhibit_images:
            uri_prefix: /uploads/images/exhibit
            upload_destination: '%kernel.project_dir%/public/uploads/images/exhibit'
        performance_images:
            uri_prefix: /uploads/images/performance
            upload_destination: '%kernel.project_dir%/public/uploads/images/performance'
        meeting_images:
            uri_prefix: /uploads/images/meeting
            upload_destination: '%kernel.project_dir%/public/uploads/images/meeting'
        workshop_images:
            uri_prefix: /uploads/images/workshop
            upload_destination: '%kernel.project_dir%/public/uploads/images/workshop'
        street_images:
            uri_prefix: /uploads/images/street
            upload_destination: '%kernel.project_dir%/public/uploads/images/street'
        event_images:
            uri_prefix: /uploads/images/event
            upload_destination: '%kernel.project_dir%/public/uploads/images/event'
